### ISSUE TITLE
PackageControl installation fails

### ISSUE THREAD

**Issue by SturmB** [Fuhrmann/keypirinha-faker-data#2]
I'm afraid the method of installing this via `PackageControl` does not currently work. Here is the output of attempting to do so:

```
09:54:08.481 PackageControl.PackageControl: Installed package 'keypirinha-faker-data'
09:54:10.217 Python: Traceback (most recent call last):
09:54:10.217 Python:   File "keypirinha_private.py", line 356, in reload_module
09:54:10.217 Python:   File "lib\importlib\__init__.py", line 126, in import_module
09:54:10.217 Python:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
09:54:10.217 Python:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
09:54:10.217 Python:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
09:54:10.217 Python:   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
09:54:10.217 Python:   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
09:54:10.217 Python:   File "keypirinha_private.py", line 246, in load_module
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\fakerdata.py", line 11, in <module>
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\__init__.py", line 4, in <module>
09:54:10.217 Python:     from faker.factory import Factory
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\factory.py", line 10, in <module>
09:54:10.217 Python:     from faker.config import DEFAULT_LOCALE, PROVIDERS, AVAILABLE_LOCALES
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\config.py", line 14, in <module>
09:54:10.217 Python:     AVAILABLE_LOCALES = find_available_locales(PROVIDERS)
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\utils\loading.py", line 32, in find_available_locales
09:54:10.217 Python:     provider_module = import_module(provider_path)
09:54:10.217 Python:   File "lib\importlib\__init__.py", line 126, in import_module
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\providers\address\__init__.py", line 6, in <module>
09:54:10.217 Python:     from .. import date_time
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\providers\date_time\__init__.py", line 11, in <module>
09:54:10.217 Python:     from dateutil import relativedelta
09:54:10.217 Python:   File "C:\Keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\dateutil\relativedelta.py", line 8, in <module>
09:54:10.217 Python:     from six import integer_types
09:54:10.217 Python: ModuleNotFoundError: No module named 'six'
```

**Comment by filviu** [comment]
Same here, latest keypirinha version, portable mode.

**Comment by Fuhrmann** [comment]
There is a new release, hope it fixes!

https://github.com/Fuhrmann/keypirinha-faker-data/releases/tag/1.0.1

**Comment by SturmB** [comment]
It appears to be working now. Thanks!
